name: in_phase
app_name: InPhase
description: A music library management tool for creating and syncing playlists between Spotify and Rekordbox.
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.8.2

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dcli: ^7.0.5
  doos:
    path: packages/doos
  drift: ^2.22.0
  equatable: ^2.0.7
  fuzzywuzzy: ^1.2.0
  glob: ^2.1.3
  image: ^4.3.0
  intl: ^0.19.0
  io: ^1.0.5
  json_annotation: ^4.9.0
  oauth2: ^2.0.3
  oxidized: ^6.2.0
  path: ^1.9.1
  rekorddart:
    git:
      url: https://github.com/jeroen-meijer/rekorddart
      ref: 1.0.2
  spotify:
    git:
      url: https://github.com/jeroen-meijer/spotify-dart
      ref: b5cee2c373a6b5f9f9d1ffb71cd956f82cce19df
  sqlite3: ^2.4.6
  uuid: ^4.5.1
  yaml: ^3.1.3
  yaml_codec: ^1.0.0

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.22.0
  json_serializable: ^6.11.1
  test: ^1.24.0
  very_good_analysis: ^9.0.0

executables:
  in_phase:

pubspec_extract:
  class_name: Pubspec
  source: pubspec.yaml
  destination: lib/src/misc/pubspec.dart
  extract-name: true
  extract-version: true
