name: rkdb_dart
app_name: rkdb
description: A Rekordbox management tool.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.2

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dcli: ^7.0.5
  doos:
    path: packages/doos
  fuzzywuzzy: ^1.2.0
  glob: ^2.1.3
  io: ^1.0.5
  json_annotation: ^4.9.0
  oxidized: ^6.2.0
  path: ^1.9.1
  rekorddart:
    path: ../rekorddart
  spotify: ^0.13.7
  uuid: ^4.5.1
  yaml: ^3.1.3
  yaml_codec: ^1.0.0

dev_dependencies:
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  test: ^1.24.0
  very_good_analysis: ^9.0.0

executables:
  rkdb:

pubspec_extract:
  class_name: Pubspec
  source: pubspec.yaml
  destination: lib/src/misc/pubspec.dart
  extract-name: true
  extract-version: true
