name: doos
version: 1.0.0
description: A simply library for type-safe local storage, both for pure Dart and Flutter apps.

environment:
  sdk: ^3.8.2

dependencies:
  equatable: ^2.0.7
  meta: ^1.17.0
  rxdart: ^0.28.0

dev_dependencies:
  checks: ^0.3.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^9.0.0
